Controllers/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using laba5_oop.Managers.Categories;
using laba5_oop.Storage.Entity;
using Microsoft.AspNetCore.Mvc;

namespace laba5_oop.Controllers
{
    public class CategoryController : Controller
    {
        readonly ICategoryManager _categoryManager;

        public CategoryController (ICategoryManager categoryManager)
        {
            _categoryManager = categoryManager;
        }

        [HttpGet]
        public async Task<ViewResult> ShowCategory()
        {
            var entity = await _categoryManager.GetAll();

            return View(entity);
        }
         
        public ViewResult AddCategory()
        {
            return View();
        }

        public async Task<ViewResult> EditCategory(Category oldEntity)
        {
            var entity = await _categoryManager.FindCategory(oldEntity.Id);
            return View(entity);
        }

        [HttpPost]
        public async Task<ActionResult> Add(CreateOrUpdateCategory createOrUpdateCategory)
        {
            await _categoryManager.AddCategory(createOrUpdateCategory);
            return RedirectToAction(nameof(ShowCategory));
        }

        public async Task<ActionResult> Remove(Category entity)
        {
            await _categoryManager.RemoveCategory(entity);
            return RedirectToAction(nameof(ShowCategory));
        }

        public async Task<ActionResult> Edit(Category oldEntity)
        {
            await _categoryManager.EditCategory(oldEntity);
            return RedirectToAction(nameof(ShowCategory));
        }
            
    }
}

Controllers/ModelCarController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using laba5_oop.Managers.ModelCars;
using laba5_oop.Storage.Entity;
using Microsoft.AspNetCore.Mvc;

namespace laba5_oop.Controllers
{
    public class ModelCarController : Controller
    {
        readonly IModelCarManager _modelCarManager;

        public ModelCarController(IModelCarManager categoryModelCar)
        {
            _modelCarManager = categoryModelCar;
        }

        [HttpGet]
        public async Task<ViewResult> ShowModelCar()
        {
            var entity = await _modelCarManager.GetAll();

            return View(entity);
        }

        public ViewResult AddModelCar()
        {
            return View();
        }

        public async Task<ViewResult> EditModelCar(ModelCar oldEntity)
        {
            var entity = await _modelCarManager.FindModelCar(oldEntity.Id);

            return View(entity);
        }

        [HttpPost]
        public async Task<ActionResult> Add(CreateOrUpdateModelCar createOrUpdateCategory)
        {
            await _modelCarManager.AddModelCar(createOrUpdateCategory);
            return RedirectToAction(nameof(ShowModelCar));
        }

        public async Task<ActionResult> Remove(ModelCar entity)
        {
            await _modelCarManager.RemoveModelCar(entity);
            return RedirectToAction(nameof(ShowModelCar));
        }

        public async Task<ActionResult> Edit(ModelCar oldEntity)
        {
            await _modelCarManager.EditModelCar(oldEntity);
            return RedirectToAction(nameof(ShowModelCar));
        }
    }
}

Controllers/OrderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using laba5_oop.Managers.Orders;
using laba5_oop.Models;
using laba5_oop.Storage.Entity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace laba5_oop.Controllers
{
    public class OrderController : Controller
    {
        readonly IOrderManager _orderManager;

        public OrderController(IOrderManager orderManager)
        {
            _orderManager = orderManager;
        }

        public async Task<ViewResult> ShowOrder()
        {
            var entity = await _orderManager.GetAll();

            return View(entity);
        }

        public ViewResult CreateOrder()
        {
            return View();
        }

        public async Task<ViewResult> Edit(Order oldEntity)
        {
            oldEntity = await _orderManager.FindId(oldEntity.Id);

            return View(oldEntity);
        }
        public async Task<ViewResult> Details(Order order)
        {
            var entity = await _orderManager.EntityForDetails(order);
            return View(entity);
        }

        [HttpPost]
        public async Task<ActionResult> InOrderFromDetail(Detail entity)
        {
            await _orderManager.AddOrder(entity);

            return RedirectToAction("ShowDetail", "Detail");
        }

        public async Task<ActionResult> Create(CreateOrUpdateOrder orUpdateOrder)
        {
            await _orderManager.CreateOrder(orUpdateOrder);
            return RedirectToAction("ShowDetail", "Detail");
        }

        public async Task<ActionResult> Remove(Order entity)
        {
            await _orderManager.RemoveOrder(entity);
            return RedirectToAction(nameof(ShowOrder));
        }

        public async Task<ActionResult> EditOrder(Order oldEntity)
        {
            await _orderManager.EditOrder(oldEntity);
            return RedirectToAction(nameof(ShowOrder));
        }

        public async Task<ActionResult> DeleteFromOrder(Guid id, Guid OrderId, string price)
        {
            decimal Price = decimal.Parse(price);
            await _orderManager.DeleteFromOrder(id, OrderId, Price);
            return RedirectToAction(nameof(ShowOrder));
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AutoMarket</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">AutoMarket</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Category" asp-action="ShowCategory">Categories</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Detail" asp-action="ShowDetail">Details</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ModelCar" asp-action="ShowModelCar">ModelCar</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Detail" asp-action="SearchMenu">SearchMenu</a>
                        </li>
                        <li class="nav-item ml-auto">
                            <form class="form-inline my-2 my-lg-0 mx-auto">
                                <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search" name="Search">
                                <input class="btn btn-outline-success my-2 my-sm-0" type="submit" value="Search" asp-area="" asp-controller="Detail" asp-action="SearchName" asp-route-search="Search">
                            </form>
                        </li>
                        <li class="nav-item ml-auto">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Order" asp-action="ShowOrder">
                                <img src="~/css/Cart.jpg" alt="Order" title="Order" style="width:25px;">Order
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - AutoMarket - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>