Controllers/BrandOfDetailController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using laba5_oop.Managers.BrandOfDetails;
using laba5_oop.Storage.Entity;
using Microsoft.AspNetCore.Mvc;

namespace laba5_oop.Controllers
{
    public class BrandOfDetailController : Controller
    {
        readonly IBrandOfDetailManager _brandOfDetailManager;

        public BrandOfDetailController(IBrandOfDetailManager brandOfDetailManager)
        {
            _brandOfDetailManager = brandOfDetailManager;
        }

        public async Task<ViewResult> Show()
        {
            var entity = await _brandOfDetailManager.GetAll();

            return View(entity);
        }

        public ViewResult Create()
        {
            return View();
        }

        public async Task<ViewResult> Edit(BrandOfDetail oldEntity)
        {
            var entity = await _brandOfDetailManager.FindBrandOfDetail(oldEntity.Id);
            return View(entity);
        }

        [HttpPost]

        public async Task<ActionResult> CreateBrand(BrandOfDetail brandOfDetailController)
        {
            await _brandOfDetailManager.AddBrandOfDetail(brandOfDetailController);

            return RedirectToAction(nameof(Show));
        }

        public async Task<ActionResult> EditBrand(BrandOfDetail oldEntity)
        {
            await _brandOfDetailManager.EditBrandOfDetail(oldEntity);
            return RedirectToAction(nameof(Show));
        }

        public async Task<ActionResult> Remove(BrandOfDetail entity)
        {
            await _brandOfDetailManager.RemoveBrandOfDetail(entity);
            return RedirectToAction(nameof(Show));
        }
    }
}

Controllers/DetailController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc.Async;
using laba5_oop.Managers.Details;
using laba5_oop.Managers.Orders;
using laba5_oop.Models;
using laba5_oop.Storage.Entity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace laba5_oop.Controllers
{
    public class DetailController : Controller
    {
        readonly IDetailManager _detailManager;

        public DetailController (IDetailManager detailManager)
        {
            _detailManager = detailManager;
        }

        public async Task<ViewResult> ShowDetail()
        {
            var entity = await _detailManager.GetAll();

            return View(entity);
        }

        public ViewResult CreateDetail()
        {
            var TaskEntity = _detailManager.CreateOrUpdateDetail();
            var entity = TaskEntity.Result;

            ViewBag.CategoryIdList = new SelectList(entity.CategoryIdList, "Id","Name", entity.CategoryIdList.Select(it => it.Id));
            ViewBag.ModelCarIdList = new SelectList(entity.ModelCarIdList, "Id","Name", entity.ModelCarIdList.Select(it => it.Id));
            ViewBag.BrandIdList = new SelectList(entity.BrandOfDetailIdList, "Id", "Name", entity.BrandOfDetailIdList.Select(it => it.Id));
            return View();
        }

        public async Task<ViewResult> DetailsOfDetail(Detail entity)
        {
            entity = await _detailManager.FindId(entity.Id);
            var orderEntity = await _detailManager.GetAllOrders();
            ViewBag.OrderIdList = new SelectList(orderEntity, "Id", "Name", orderEntity.Select(it => it.Id));
            return View(entity);
        }

        public async Task<ViewResult> Edit(Detail oldEntity)
        {
            oldEntity = await _detailManager.FindId(oldEntity.Id);
            var entity = await _detailManager.CreateOrUpdateDetail();

            ViewBag.CategoryIdList = new SelectList(entity.CategoryIdList, "Id", "Name", entity.CategoryIdList.Select(it => it.Id));
            ViewBag.ModelIdList = new SelectList(entity.ModelCarIdList, "Id", "Name", entity.ModelCarIdList.Select(it => it.Id));
            ViewBag.BrandIdList = new SelectList(entity.BrandOfDetailIdList, "Id", "Name", entity.BrandOfDetailIdList.Select(it => it.Id));
            return View(oldEntity);
        }

        public ViewResult SearchResult(IEnumerable<Detail> entities)
        {
            return View(entities);
        }

        public async Task<ViewResult> SearchMenu()
        {
            var entity = await _detailManager.CreateOrUpdateDetail();
            entity.CategoryIdList.Add(new Category { Name = "" });
            entity.ModelCarIdList.Add(new ModelCar { Name = "" });
            entity.BrandOfDetailIdList.Add(new BrandOfDetail { Name = "" });

            ViewBag.CategoryIdList = new SelectList(entity.CategoryIdList, "Id", "Name", entity.CategoryIdList.Select(it => it.Id));
            ViewBag.ModelCarIdList = new SelectList(entity.ModelCarIdList, "Id", "Name", entity.ModelCarIdList.Select(it => it.Id));
            ViewBag.BrandIdList = new SelectList(entity.BrandOfDetailIdList, "Id", "Name", entity.BrandOfDetailIdList.Select(it => it.Id));
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> Create(CreateOrUpdateDetail createOrUpdateDetail)
        {
            await _detailManager.AddDetail(createOrUpdateDetail);
            return RedirectToAction(nameof(ShowDetail));
        }
        public async Task<ActionResult> Remove(Detail entity)
        {
            await _detailManager.RemoveDetail(entity);
            return RedirectToAction(nameof(ShowDetail));
        }

        public async Task<ActionResult> EditDetail(Detail oldEntity)
        {
            await _detailManager.EditDetail(oldEntity);
            return RedirectToAction(nameof(ShowDetail));
        }

        public async Task<ActionResult> Search(SearchModel searchModel)
        {
            var entity = await _detailManager.SearchFull(searchModel);
            return View(nameof(SearchResult), entity);
        }

        public async Task<ActionResult> SearchName(string Search)
        {
            var entities = await _detailManager.SearchName(Search);
            return View(nameof(SearchResult),entities);
        }
    }
}

Views/BrandOfDetail/Create.cshtml
@model laba5_oop.Storage.Entity.BrandOfDetail

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>BrandOfDetail</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="CreateBrand">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-controller="Home" asp-action="Index">Back to List</a>
</div>

Views/BrandOfDetail/Edit.cshtml
@model laba5_oop.Storage.Entity.BrandOfDetail

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>BrandOfDetail</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="EditBrand">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Show">Back to List</a>
</div>

Views/BrandOfDetail/Show.cshtml
@model ListBrandWithListDetail

@{
    ViewData["Title"] = "Show";
}

<h1>Show</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
@for (int i = 0; i < Model.BrandOfDetails.Count(); i++)
{
<div class="col-2 text-info">
    <h3>@Model.BrandOfDetails[i].Name</h3> <a asp-action="Edit" asp-route-id="@Model.BrandOfDetails[i].Id">Edit</a> |
    <a asp-action="Remove" asp-route-id="@Model.BrandOfDetails[i].Id">Delete</a>
</div>
    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Detail[i][i].Name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Detail[i][i].Price)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Detail[i][i].Category)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Detail[i][i].ModelCar)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.Detail[i])
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Price)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Category.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ModelCar.Name)
                    </td>
                    <td>
                        <a asp-controller="Detail" asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                        <a asp-controller="Detail" asp-action="DetailsOfDetail" asp-route-id="@item.Id">Details</a> |
                        <a asp-controller="Detail" asp-action="Remove" asp-route-id="@item.Id">Delete</a> |
                        <a asp-controller="Detail" asp-action="DetailsOfDetail" asp-route-id="@item.Id" class="btn btn-danger">In cart </a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
}