Controllers/CarForSoldController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using laba5_oop.Managers.CarForSolds;
using laba5_oop.Models;
using laba5_oop.Storage.Entity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace laba5_oop.Controllers
{
    public class CarForSoldController : Controller
    {
        readonly ICarForSoldManager _carForSoldManager;

        public CarForSoldController(ICarForSoldManager CarForSoldManager)
        {
            _carForSoldManager = CarForSoldManager;
        }
        public async Task<ViewResult> Show()
        {
            var entity = await _carForSoldManager.GetAll();

            return View(entity);
        }
        public ViewResult Create()
        {
            var TaskEntity = _carForSoldManager.CreateOrUpdateCarForSold();
            var entity = TaskEntity.Result;

            ViewBag.ModelCarIdList = new SelectList(entity.ModelCarIdList, "Id", "Name", entity.ModelCarIdList.Select(it => it.Id));
            return View();
        }
        public async Task<ViewResult> Edit(CarForSold oldEntity)
        {
            oldEntity = await _carForSoldManager.FindId(oldEntity.Id);
            var entity = await _carForSoldManager.CreateOrUpdateCarForSold();

            ViewBag.ModelIdList = new SelectList(entity.ModelCarIdList, "Id", "Name", entity.ModelCarIdList.Select(it => it.Id));
            return View(oldEntity);
        }

        public ViewResult SearchResult(IEnumerable<CarForSold> entities)
        {
            return View(entities);
        }

        public async Task<ViewResult> Detail(CarForSold entity)
        {
            entity = await _carForSoldManager.FindId(entity.Id);
            return View(entity);
        }

        [HttpPost]
        public async Task<ActionResult> CreateCar(CreateOrUpdateCarForSold createOrUpdateCarForSold)
        {
            await _carForSoldManager.AddCarForSold(createOrUpdateCarForSold);
            return RedirectToAction(nameof(Show));
        }
        public async Task<ActionResult> EditCar(CarForSold oldEntity)
        {
            await _carForSoldManager.EditCarForSold(oldEntity);
            return RedirectToAction(nameof(Show));
        }
        public async Task<ActionResult> Search(SearchModel searchModel)
        {
            var entity = await _carForSoldManager.SearchFull(searchModel);
            return View(nameof(SearchResult), entity);
        }

        public async Task<ActionResult> SearchName(string Search)
        {
            var entities = await _carForSoldManager.SearchName(Search);
            return View(nameof(SearchResult), entities);
        }

        public async Task<ActionResult> Delete(CarForSold entity)
        {
            await _carForSoldManager.RemoveCarForSold(entity);
            return RedirectToAction(nameof(Show));
        }
    }
}

Controllers/DetailController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc.Async;
using laba5_oop.Managers.Details;
using laba5_oop.Managers.Orders;
using laba5_oop.Models;
using laba5_oop.Storage.Entity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace laba5_oop.Controllers
{
    public class DetailController : Controller
    {
        readonly IDetailManager _detailManager;

        public DetailController (IDetailManager detailManager)
        {
            _detailManager = detailManager;
        }

        public async Task<ViewResult> ShowDetail()
        {
            var entity = await _detailManager.GetAll();

            return View(entity);
        }

        public ViewResult CreateDetail()
        {
            var TaskEntity = _detailManager.CreateOrUpdateDetail();
            var entity = TaskEntity.Result;

            ViewBag.CategoryIdList = new SelectList(entity.CategoryIdList, "Id","Name", entity.CategoryIdList.Select(it => it.Id));
            ViewBag.ModelCarIdList = new SelectList(entity.ModelCarIdList, "Id","Name", entity.ModelCarIdList.Select(it => it.Id));
            ViewBag.BrandIdList = new SelectList(entity.BrandOfDetailIdList, "Id", "Name", entity.BrandOfDetailIdList.Select(it => it.Id));
            return View();
        }

        public async Task<ViewResult> DetailsOfDetail(Detail entity)
        {
            entity = await _detailManager.FindId(entity.Id);
            var orderEntity = await _detailManager.GetAllOrders();
            ViewBag.OrderIdList = new SelectList(orderEntity, "Id", "Name", orderEntity.Select(it => it.Id));
            return View(entity);
        }

        public async Task<ViewResult> Edit(Detail oldEntity)
        {
            oldEntity = await _detailManager.FindId(oldEntity.Id);
            var entity = await _detailManager.CreateOrUpdateDetail();

            ViewBag.CategoryIdList = new SelectList(entity.CategoryIdList, "Id", "Name", entity.CategoryIdList.Select(it => it.Id));
            ViewBag.ModelIdList = new SelectList(entity.ModelCarIdList, "Id", "Name", entity.ModelCarIdList.Select(it => it.Id));
            ViewBag.BrandIdList = new SelectList(entity.BrandOfDetailIdList, "Id", "Name", entity.BrandOfDetailIdList.Select(it => it.Id));
            return View(oldEntity);
        }

        public ViewResult SearchResult(IEnumerable<Detail> entities)
        {
            return View(entities);
        }

        public async Task<ViewResult> SearchMenu()
        {
            var entity = await _detailManager.CreateOrUpdateDetail();
            entity.CategoryIdList.Add(new Category { Name = "" });
            entity.ModelCarIdList.Add(new ModelCar { Name = "" });
            entity.BrandOfDetailIdList.Add(new BrandOfDetail { Name = "" });

            ViewBag.CategoryIdList = new SelectList(entity.CategoryIdList, "Id", "Name", entity.CategoryIdList.Select(it => it.Id));
            ViewBag.ModelCarIdList = new SelectList(entity.ModelCarIdList, "Id", "Name", entity.ModelCarIdList.Select(it => it.Id));
            ViewBag.BrandIdList = new SelectList(entity.BrandOfDetailIdList, "Id", "Name", entity.BrandOfDetailIdList.Select(it => it.Id));
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> Create(CreateOrUpdateDetail createOrUpdateDetail)
        {
            await _detailManager.AddDetail(createOrUpdateDetail);
            return RedirectToAction(nameof(ShowDetail));
        }
        public async Task<ActionResult> Remove(Detail entity)
        {
            await _detailManager.RemoveDetail(entity);
            return RedirectToAction(nameof(ShowDetail));
        }

        public async Task<ActionResult> EditDetail(Detail oldEntity)
        {
            await _detailManager.EditDetail(oldEntity);
            return RedirectToAction(nameof(ShowDetail));
        }

        public async Task<ActionResult> Search(SearchModel searchModel)
        {
            var entity = await _detailManager.SearchFull(searchModel);
            return View(nameof(SearchResult), entity);
        }

        public async Task<ActionResult> SearchName(string Search)
        {
            var entities = await _detailManager.SearchName(Search);
            return View(nameof(SearchResult),entities);
        }
    }
}

Controllers/OrderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using laba5_oop.Managers.Orders;
using laba5_oop.Models;
using laba5_oop.Storage.Entity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace laba5_oop.Controllers
{
    public class OrderController : Controller
    {
        readonly IOrderManager _orderManager;

        public OrderController(IOrderManager orderManager)
        {
            _orderManager = orderManager;
        }

        public async Task<ViewResult> ShowOrder()
        {
            var entity = await _orderManager.GetAll();

            return View(entity);
        }

        public ViewResult CreateOrder()
        {
            return View();
        }

        public async Task<ViewResult> Edit(Order oldEntity)
        {
            oldEntity = await _orderManager.FindId(oldEntity.Id);

            return View(oldEntity);
        }
        public async Task<ViewResult> Details(Order order)
        {
            var entity = await _orderManager.EntityForDetails(order);
            return View(entity);
        }

        [HttpPost]
        public async Task<ActionResult> InOrderFromDetail(Detail entity)
        {
            await _orderManager.AddOrder(entity);

            return RedirectToAction("ShowDetail", "Detail");
        }

        public async Task<ActionResult> Create(CreateOrUpdateOrder orUpdateOrder)
        {
            await _orderManager.CreateOrder(orUpdateOrder);
            return RedirectToAction("ShowDetail", "Detail");
        }

        public async Task<ActionResult> Remove(Order entity)
        {
            await _orderManager.RemoveOrder(entity);
            return RedirectToAction(nameof(ShowOrder));
        }

        public async Task<ActionResult> EditOrder(Order oldEntity)
        {
            await _orderManager.EditOrder(oldEntity);
            return RedirectToAction(nameof(ShowOrder));
        }

        public async Task<ActionResult> DeleteFromOrder(Guid id, Guid OrderId, string price)
        {
            decimal Price = decimal.Parse(price);
            await _orderManager.DeleteFromOrder(id, OrderId, Price);
            return RedirectToAction(nameof(ShowOrder));
        }
    }
}

Views/Detail/CreateDetail.cshtml
@model laba5_oop.Managers.Details.CreateOrUpdateDetail

@{
    ViewData["Title"] = "CreateDetail";
}

<h1>Create detail</h1>

<h4>Detail</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Category" class="control-label"></label>
                <select asp-for="Category" class="form-control" asp-items="ViewBag.CategoryIdList"></select>
            </div>
            <div class="form-group">
                <label asp-for="ModelCar" class="control-label"></label>
                <select asp-for="ModelCar" class="form-control" asp-items="ViewBag.ModelCarIdList"></select>
            </div>
            <div class="form-group">
                <label asp-for="BrandOfDetail" class="control-label"></label>
                <select asp-for="BrandOfDetail" class="form-control" asp-items="ViewBag.BrandIdList"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="ShowDetail">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Detail/DetailsOfDetail.cshtml
@model laba5_oop.Storage.Entity.Detail

@{
    ViewData["Title"] = "DetailsOfDetail";
}

<h1></h1>

<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a asp-controller="Home" asp-action="Index">Home</a></li>
        <li class="breadcrumb-item"><a asp-controller="Detail" asp-action="ShowDetail">Details</a></li>
        <li class="breadcrumb-item active" aria-current="page">@Html.DisplayFor(model => model.Name)</li>
    </ol>
</nav>
<div>
    <h4>Detail</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Category)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Category.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ModelCar)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ModelCar.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Brand)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Brand.Name)
        </dd>
    </dl>
</div>
<a asp-action="InOrderFromDetail" class="btn btn-danger" data-toggle="modal" data-target="#ModalCart">In cart </a>
<div class="modal fade" id="ModalCart" tabindex="-1" role="dialog" aria-labelledby="ModalCartLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="ModalCartLabel">Detail will be added to the cart </h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form asp-controller="Order" asp-action="InOrderFromDetail" asp-route-id="@Model.Id">
                    <div class="text-danger"></div>
                    <div class="form-group">
                        <b><label for="Name" class="col-form-label">Name of detail:</label></b>
                        <br /><label asp-for="Name" class="col-form-label">@Model.Name</label>
                    </div>
                    <div class="form-group">
                        <b><label for="Price" class="col-form-label">Price:</label></b>
                        <br /><label asp-for="Price" class="col-form-label">@Model.Price</label>
                    </div>
                    <div class="form-group">
                        <b><label for="Price" class="col-form-label">In order:</label></b>
                        <select asp-for="CategoryId" class="form-control" asp-items="ViewBag.OrderIdList"></select>
                        <p>
                            <a asp-controller="Order" asp-action="CreateOrder">Create new order</a>
                        </p>
                        <input class="btn btn-outline-success my-2 my-sm-0" type="submit" value="Continue">
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="ShowDetail">Back to List</a>
</div>

Views/Detail/Edit.cshtml
@model laba5_oop.Storage.Entity.Detail

@{
    ViewData["Title"] = "View";
}

<h1>View</h1>

<h4>Detail</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="EditDetail">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CategoryId" class="control-label"></label>
                <select asp-for="CategoryId" class="form-control" asp-items="ViewBag.CategoryIdList"></select>
                <span asp-validation-for="CategoryId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ModelId" class="control-label"></label>
                <select asp-for="ModelId" class="form-control" asp-items="ViewBag.ModelIdList"></select>
                <span asp-validation-for="ModelId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BrandId" class="control-label"></label>
                <select asp-for="BrandId" class="form-control" asp-items="ViewBag.BrandIdList"></select>
                <span asp-validation-for="BrandId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="ShowDetail">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Detail/SearchMenu.cshtml
@model SearchModel

@{
    ViewData["Title"] = "SearchMenu";
}

<h1>SearchMenu</h1>

<h4>Detail</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Search">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CategoryId" class="control-label"></label>
                <select asp-for="CategoryId" class="form-control" asp-items="ViewBag.CategoryIdList"></select>
                <span asp-validation-for="CategoryId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ModelCarId" class="control-label"></label>
                <select asp-for="ModelCarId" class="form-control" asp-items="ViewBag.ModelCarIdList"></select>
                <span asp-validation-for="ModelCarId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BrandId" class="control-label"></label>
                <select asp-for="BrandId" class="form-control" asp-items="ViewBag.BrandIdList"></select>
                <span asp-validation-for="BrandId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Search" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<h4>Detail</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-controller="CarForSold" asp-action="Search">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Mileage" class="control-label"></label>
                <input asp-for="Mileage" class="form-control" />
                <span asp-validation-for="Mileage" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ModelCarId" class="control-label"></label>
                <select asp-for="ModelCarId" class="form-control" asp-items="ViewBag.ModelCarIdList"></select>
                <span asp-validation-for="ModelCarId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Search" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-controller="Home" asp-action="Index">Back to List</a>
</div>

Views/Detail/SearchResult.cshtml
@model IEnumerable<laba5_oop.Storage.Entity.Detail>

@{
    ViewData["Title"] = "SearchName";
}

<h1>Search result</h1>

@if (Model.Count() == 0)
{
    <div class="alert alert-warning" role="alert">
        Not found!
    </div>
}
else
{
    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Price)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Category)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.ModelCar)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Brand)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Price)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Category.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ModelCar.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Brand.Name)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                    <a asp-action="DetailsOfDetail" asp-route-id="@item.Id">Details</a> |
                    <a asp-action="Remove" asp-route-id="@item.Id">Delete</a> |
                    <a asp-action="DetailsOfDetail" asp-route-id="@item.Id" class="btn btn-danger">In cart </a>
                </td>
            </tr>
            }
        </tbody>
    </table>
}

Views/Detail/ShowDetail.cshtml
@model IEnumerable<laba5_oop.Storage.Entity.Detail>

@{
    ViewData["Title"] = "ShowDetail";
}

<h1>Show Details</h1>

<p>
    <a asp-action="CreateDetail">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Price)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Category)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ModelCar)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Brand)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Price)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Category.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ModelCar.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Brand.Name)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="DetailsOfDetail" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Remove" asp-route-id="@item.Id">Delete</a> |
                <a asp-action="DetailsOfDetail" asp-route-id="@item.Id" class="btn btn-danger">In cart </a>
            </td>
        </tr>
}
    </tbody>
</table>